Appunte/urls.py
from django.urls import path
from .views import views

app_name='Appunte'

urlpatterns = [
        # INICIO
        path(r'', views.index, name="index"),

     
        # PERFIL
        path('accounts/profile/', views.PerfilUsuario, name='perfil'),
        path('accounts/salir/', views.salir, name='salir'),

        # COURSE 
        path('cursos/lista', views.coursesList, name="course-list"),

        # TOPIC 
        path('cursos/lista/<int:pk>', views.topicList, name="topic-list"),
        path('cursos/lista/subtopic/<int:pk>', views.subtopicList, name="subtopic-list"),

        # Question 
        path('cursos/pregunta/<int:pk>', views.showQuestion, name="question-show"),
]

CourseApp/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path
from django.contrib.auth import views as auth_views
from Appunte.views import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Appunte.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html',redirect_field_name='courses/list.html'), name='login'),
    path('accounts/register/', views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Appunte/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from .managers import CustomUserManager

# USUARIO CUSTOM
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=264)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    rol = models.CharField(max_length=12,default="student")
    profile_pic = models.ImageField(upload_to='user_profile',blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email



# CURSO
class Course(models.Model):
    name = models.CharField(max_length=100) 
    description = models.CharField(max_length=5000) 
    teacher =  models.CharField(max_length=100) 
    is_pay = models.BooleanField(default=False)
    price = models.CharField(max_length=15)
    published = models.BooleanField(default=False)
    course_pic = models.ImageField(upload_to='course_profile',blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.name


# Topic
class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE) 
    name = models.CharField(max_length=1000) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.name        


# Subtopic
class Subtopic(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) 
    name = models.CharField(max_length=1000) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.name   


class Question(models.Model):
    subtopic = models.ForeignKey(Subtopic, on_delete=models.CASCADE) 
    sort = models.IntegerField()
    content = models.TextField() 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.content   


class Answer(models.Model):
    answer = models.ForeignKey(Question, on_delete=models.CASCADE) 
    content = models.TextField() 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.content                      

Appunte/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User, Course


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'rol')


class RegistrationForm(forms.Form):
    class Meta:
        model = User
        fields = ('email', 'username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    username = forms.CharField(
        label='Nombre de Usuario',
        max_length=30,
    )

    email = forms.EmailField(
        label='Correo',
    )

    password = forms.CharField(
        label='Contraseña',
    )

    def clean_username(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data['username']
        if User.users.filter(username=username):
            self.add_error(
                'username',
                forms.ValidationError("User Exists")
            )

        return username

    def clean_email(self):
        cleaned_data = super(RegistrationForm, self).clean()
        email = cleaned_data['email']
        if User.users.filter(email=email):
            self.add_error(
                'email',
                forms.ValidationError(
                    "Mail exists")
            )

        return email

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()

    def save(self):
        cleaned_data = super(RegistrationForm, self).clean()

        user_data = {
            'email': cleaned_data['email'],
            'username': cleaned_data['username'],
        }
        user = User(**user_data)
        user.set_password(cleaned_data['password'])
        user.save()

        return user


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'description', 'teacher', 'price', 'is_published', 'picture')

Appunte/views/views.py
from django.shortcuts import render, redirect
from django import forms
from ..forms import CourseForm, CustomUserCreationForm, RegistrationForm
from ..models import Course, Topic, Subtopic, Question, Answer
from ..managers import CustomUserManager

from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

def index(request):
    return render(request, 'index.html', {})



###############    Views de Usuarios

def PerfilUsuario(request):
    return render(request, 'index.html', {})

def salir(request):
    logout(request)
    # Redirect to a success page.
    return redirect('/')    


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../../cursos/lista')
    
    form = RegistrationForm()
    args = {'form': form}
    return render(request, 'registration/register.html', {}) 





###########################     Views of Courses     #######################

def coursesList(request):
    courses = Course.objects.all()
    if not request.user.is_authenticated:
        return redirect('/accounts/login/')

    return render(request, 'courses/list.html', {"courses":courses})


def palmera(request):
        
    return render(request, 'palmera.html', {})    



###########################     Views of Topics     #######################

def topicList(request, pk):
    topics = Topic.objects.filter(course=pk)
    if not request.user.is_authenticated:
        return redirect('/accounts/login/')

    return render(request, 'topic/list.html', {"topics":topics})




 
def subtopicList(request, pk):
    subtopics = Subtopic.objects.filter(topic=pk)
    if not request.user.is_authenticated:
        return redirect('/accounts/login/')

    return render(request, 'subtopic/list.html', {"subtopics":subtopics})   



def showQuestion(request, pk):
    questions = Question.objects.filter(subtopic=pk)
    if not request.user.is_authenticated:
        return redirect('/accounts/login/')

    return render(request, 'question/show.html', {"questions":questions} )       



def showAnswer(request, pk):
    answer = Answer.objects.filter(question=pk)
    if not request.user.is_authenticated:
        return redirect('/accounts/login/')

   # return render(request, 'question/list.html', {"answers":answers})     

Appunte/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appunte</title>

    <!-- Latest compiled and minified CSS -->
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <!-- <link rel="icon" href="{% static '/img/dog.ico' %}"> -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.2/umd/popper.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static '/css/styles.css' %}">

    <script src="https://kit.fontawesome.com/5a5ef1cb8c.js" crossorigin="anonymous"></script>

    <!-- DATATABLES -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

</head>

<body>


<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">

        <li class="nav-item">
            {% if user.is_authenticated %}
                <!-- INICIO  (TODOS) -->
                    <a class="nav-link" href="{% url 'Appunte:index' %}"> <i class="fa fa-home"
                                                                             style="margin-right: 5px;"></i> Inicio</a>
            {% else %}
                <!-- EN CASO DE NO TENER SESIÓN ACTIVA -->
                <!-- INICIAR SESIÓN  (TODOS) -->
                <a class="nav-link" href="#"> <i class="fa fa-home" style="margin-right: 5px;"></i> Inicio</a>
            {% endif %}
        </li>

        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item borde-right">
            {% if user.is_authenticated %}
                    <a class="nav-link" style="padding-right: 30px;" href="#">
                        <i class="fa fa-user" style="margin-right: 5px;"></i>{{ user.email }} - {{ user.rol }}
                    </a>
            {% else %}
                <a class="nav-link" style="padding-right: 30px;" href="{% url 'register' %}">
                    <i class="fa fa-sign-in" style="margin-right: 5px;"></i>Registrate
                </a>

            {% endif %}
            </li>

            <li class="nav-item borde-right">
            {% if user.is_authenticated %}
                    <a class="nav-link" style="padding-right: 30px;" href="{% url 'Appunte:salir' %}">
                        <i class="fa fa-sign-out" style="margin-right: 5px;"></i>Salir
                    </a>
            {% else %}

                    <a class="nav-link" style="padding-right: 30px;" href="{% url 'login' %}">
                        <i class="fa fa-sign-in" style="margin-right: 5px;"></i>Iniciar sesión
                    </a>
            {% endif %}
            </li>

        </ul>
    </div>
</nav>



{% block content %}


{% endblock %}


</body>

</html>

Appunte/templates/courses/list.html
{% extends "base.html" %}

{% block content %}

<div class="background-course">

    <h1> Lista de Cursos </h1>


    <div class="row" style="padding-left: 40px; padding-top: 40px;">

        {% for course in courses %}
        <div class="card m-2" style="width: 18rem;" >
            {% if course.course_pic %}
            <img src="{{course.course_pic.url}}"  class="card-img-top" width="140" height="180" alt="Card image cap">
            {% else %}
            {% endif %}
            <div class="card-body">
            <h5 class="card-title">{{ course.name }}</h5>
            <p class="card-text">{{ course.description }}</p>
            <p class="card-text">Profesor: {{ course.teacher }}</p>
            <a href="{% url 'Appunte:topic-list' course.id %}" class="btn btn-primary">Ver Curso</a>
            </div>
        </div>
        {% endfor %}

    </div>
</div>



{% endblock %}

Appunte/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="background-landing">
        <div class="prehome-video-content-top hidden-xs">
            <div class="col-md-1 col-md-offset-0">

            </div>

        </div>

        <div class="prehome-video-content" style="padding: 100px;">
            <div class="col-md-4 col-md-offset-1 text-home">

                APPUNTE
                <p><b>Descubre la nueva forma de estudiar!</b>
                    Regístrate o inicia sesión y prepárate para tus exámenes.
                    <span>Puedes utilizarlo en tu celular también.</span>
                    <a href="https://play.google.com/store/apps/details?id=com.ionicbyrequest.appunte" target="_blank"
                       class="default-blue-button">Android</a>
                    <a href="https://itunes.apple.com/cl/app/appunte/id1182837147?mt=8" target="_blank"
                       class="default-blue-button">IOS</a>
                </p>
            </div>
            <div class="col-md-5 col-md-offset-0">

            </div>
        </div>
    </div>

    <div class="prehome-video-content-bottom visible-xs">
        <div class="col-md-6 margin-top-2">
            Visita nuestro canal en <a
                href="https://www.youtube.com/channel/UCmLwU-OQUX5qTTSk0SquTpw"><b>YOUTUBE</b></a>
        </div>
        <div class="col-md-6 margin-top-1">

            Siguenos en
            <a href="https://www.facebook.com/appunte/" target="_blank"></a>
            <a href="https://www.instagram.com/appunte.cl/" target="_blank"></a>

        </div>
    </div>



    <!-- ENTER modal -->
    <div id="modal_enter" class="modal fade modal-session" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">

                <div class="modal-header text-center" style="padding-bottom: 0;">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                         width="182.353px" height="172.548px" viewBox="0 0 182.353 172.548"
                         enable-background="new 0 0 182.353 172.548"
                         xml:space="preserve">
          <g>
            <polygon fill="#8F908F"
                     points="62.378,37.049 38.161,57.838 56.163,82.056 50.27,98.129 90.882,152.782 	"></polygon>
              <polygon fill="#4891CE" points="62.378,37.049 82.284,47.979 67.501,57.844 	"></polygon>
              <polygon fill="#3168B2" points="82.284,47.979 67.938,59.624 67.501,57.844 	"></polygon>
              <polygon fill="#8F908F"
                       points="119.388,37.049 143.604,57.838 125.603,82.056 131.497,98.129 90.882,152.782 	"></polygon>
              <polygon fill="#4891CE" points="119.388,37.049 99.481,47.979 114.265,57.844 	"></polygon>
              <polygon fill="#3168B2" points="99.481,47.979 113.827,59.624 114.265,57.844 	"></polygon>
              <polygon fill="#EF3A37" points="90.882,65.861 96.79,65.861 104.224,53.525 97.956,48.583 90.882,48.583 83.81,48.583
						77.542,53.525 84.976,65.861 	"></polygon>
              <polygon fill="#EF3A37"
                       points="90.882,152.782 78.581,102.832 84.976,67.227 90.882,67.227 96.79,67.227 103.185,102.832 	"></polygon>
              <path fill="#EE3332" d="M84.976,65.902c0,0,1.527-2.492,5.947-2.492s5.867,2.492,5.867,2.492H84.976z"></path>
              <path fill="#EE3332" d="M81.856,116.132c0,0,4.098,9.043,9.025,9.043c4.93,0,9.027-9.043,9.027-9.043l-9.027,36.65L81.856,116.132z
						"></path>
          </g>
        </svg>
                    <h3 class="font-weight-300"> ¡BIENVENIDO! </h3>
                </div>


                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="form-group">

                            </div>
                            <div class="form-group" style="margin-bottom: 0;">

                                <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#myModalRecover">¿Olvidaste
                                    tu
                                    contraseña?</a>
                            </div>
                            <br>
                            <button type="submit" class="btn default-button" id="login-submit">Entrar</button>

                        </div>
                    </div>
                </div>
                <br><br>
                <div class="modal-footer">

                    <a class="btn fb-button" href="#">Conéctate con Facebook</a>

                </div>

            </div>
        </div>
    </div>




{% endblock %}

Appunte/templates/question/show.html
{% extends "base.html" %}

{% block content %}



    <h1> Preguntas </h1>

      
    {% for question in questions %}
    
        {% if question.id == 1 %}
            <h3>{{ question.content }}</h3>
        {% else %}

        {% endif %}

    {% endfor %}





{% endblock %}

Appunte/templates/subtopic/list.html
{% extends "base.html" %}

{% block content %}



    <h1> Contenido del Curso </h1>

        {% for subtopic in subtopics %}

            <a href="{% url 'Appunte:question-show' subtopic.id %}">{{ subtopic.name }}</a>
            <h5></h5>
            
        {% endfor %}





{% endblock %}

Appunte/templates/topic/list.html
{% extends "base.html" %}

{% block content %}



    <h1> Contenido del Curso </h1>

        {% for topic in topics %}
        <a href="{% url 'Appunte:subtopic-list' topic.id %}">{{ topic.name }}</a>
            <h5></h5>

        {% endfor %}





{% endblock %}